-- eu ma conectez cu
-- Hostname: localhost
-- Port: 1521
-- Service name: XEPDB1

-- Dupa ce rulati asta, verificati cu
-- SELECT * FROM dual@link_am;
-- SELECT * FROM dual@link_eu;

ALTER SESSION SET CONTAINER = orclpdb;

-- Creare utilizatori
CREATE USER BDDALL IDENTIFIED BY 1234;
CREATE USER ARTGALLERY_EU IDENTIFIED BY parola_eu;
CREATE USER ARTGALLERY_AM IDENTIFIED BY parola_am;
CREATE USER ARTGALLERY_GLOBAL IDENTIFIED BY parola_global;

-- Acordare privilegii
GRANT DBA TO BDDALL, ARTGALLERY_EU, ARTGALLERY_AM, ARTGALLERY_GLOBAL;

-- Cote de stocare
GRANT UNLIMITED TABLESPACE TO BDDALL;
GRANT UNLIMITED TABLESPACE TO ARTGALLERY_EU;
GRANT UNLIMITED TABLESPACE TO ARTGALLERY_AM;
GRANT UNLIMITED TABLESPACE TO ARTGALLERY_GLOBAL;

-- Crearea legăturilor de baze de date (Database Links)
CREATE PUBLIC DATABASE LINK link_am CONNECT TO ARTGALLERY_AM IDENTIFIED BY parola_am USING 'localhost:1521/XEPDB1';
CREATE PUBLIC DATABASE LINK link_eu CONNECT TO ARTGALLERY_EU IDENTIFIED BY parola_eu USING 'localhost:1521/XEPDB1';
CREATE PUBLIC DATABASE LINK link_global CONNECT TO ARTGALLERY_GLOBAL IDENTIFIED BY parola_global USING 'localhost:1521/XEPDB1';

COMMIT;