
------------------------------------------------------------
cerinta 1
------------------------------------------------------------

-- Connect to root container
ALTER SESSION SET CONTAINER = CDB$ROOT;

-- Create the second PDB as a clone of seed
CREATE PLUGGABLE DATABASE ORCLPDB2
  ADMIN USER pdbadmin IDENTIFIED BY admin
  FILE_NAME_CONVERT=('pdbseed','orclpdb2');

ALTER PLUGGABLE DATABASE ORCLPDB2 OPEN;
ALTER PLUGGABLE DATABASE ORCLPDB2 SAVE STATE;
ALTER SYSTEM REGISTER;

-- Verify
SELECT name, open_mode FROM v$pdbs;



-- =============================================================
-- Script de rulat pe DB1 (ORCLPDB) ca SYS / SYSDBA
-- BDDALL, ARTGALLERY_AM, ARTGALLERY_GLOBAL
-- =============================================================

ALTER PLUGGABLE DATABASE ORCLPDB OPEN;
ALTER SESSION SET CONTAINER = ORCLPDB;

CREATE USER BDDALL              IDENTIFIED BY 1234;
CREATE USER ARTGALLERY_AM       IDENTIFIED BY parola_am;
CREATE USER ARTGALLERY_GLOBAL   IDENTIFIED BY parola_global;

GRANT DBA TO BDDALL, ARTGALLERY_AM, ARTGALLERY_GLOBAL;
GRANT UNLIMITED TABLESPACE TO BDDALL;
GRANT UNLIMITED TABLESPACE TO ARTGALLERY_AM;
GRANT UNLIMITED TABLESPACE TO ARTGALLERY_GLOBAL;


GRANT SELECT, INSERT, UPDATE, DELETE ON EXHIBITOR_AM           TO ARTGALLERY_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON EXHIBITION_AM          TO ARTGALLERY_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON ARTWORK_EXHIBITION_AM  TO ARTGALLERY_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON LOAN_AM                TO ARTGALLERY_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON GALLERY_REVIEW_AM      TO ARTGALLERY_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON ARTWORK_DETAILS        TO ARTGALLERY_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON ARTIST_AM              TO ARTGALLERY_GLOBAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON COLLECTION_AM          TO ARTGALLERY_GLOBAL;

-- =============================================================
-- Script de rulat pe DB2 (ORCLPDB2) ca SYS / SYSDBA
-- ARTGALLERY_EU
-- =============================================================

ALTER SESSION SET CONTAINER = ORCLPDB2;

CREATE USER ARTGALLERY_EU IDENTIFIED BY parola_eu;
GRANT DBA TO ARTGALLERY_EU;
GRANT UNLIMITED TABLESPACE TO ARTGALLERY_EU;


