
alter session set container = orclpdb;
alter pluggable database orclpdb open;


CREATE USER ART_GALLERY_DW
  IDENTIFIED BY ART_GALLERY_DW
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO ART_GALLERY_DW;


ALTER USER ART_GALLERY_DW IDENTIFIED BY ART_GALLERY_DW ACCOUNT UNLOCK;


SELECT username, account_status
FROM dba_users
WHERE username = 'ART_GALLERY_DW';


ALTER USER ART_GALLERY_DW IDENTIFIED BY ART_GALLERY_DW;

GRANT CREATE SESSION TO ART_GALLERY_DW;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO ART_GALLERY_DW;
GRANT UNLIMITED TABLESPACE TO ART_GALLERY_DW



CREATE USER ART_GALLERY_OLTP
  IDENTIFIED BY ART_GALLERY_OLTP
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;
  
GRANT CONNECT, RESOURCE TO ART_GALLERY_OLTP;
ALTER USER ART_GALLERY_OLTP IDENTIFIED BY ART_GALLERY_OLTP ACCOUNT UNLOCK;
GRANT CREATE SESSION TO ART_GALLERY_OLTP;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO ART_GALLERY_OLTP;
GRANT UNLIMITED TABLESPACE TO ART_GALLERY_OLTP;
GRANT CREATE MATERIALIZED VIEW TO ART_GALLERY_OLTP;




GRANT CREATE DIMENSION TO ART_GALLERY_DW;


GRANT SELECT ON ART_GALLERY_OLTP.ARTIST     TO ART_GALLERY_DW;
GRANT SELECT ON ART_GALLERY_OLTP.ARTWORK    TO ART_GALLERY_DW;
GRANT SELECT ON ART_GALLERY_OLTP.EXHIBITION TO ART_GALLERY_DW;
GRANT SELECT ON ART_GALLERY_OLTP.LOCATION   TO ART_GALLERY_DW;
GRANT SELECT ON ART_GALLERY_OLTP.GALLERY_REVIEW TO ART_GALLERY_DW;

SELECT username, account_status
FROM dba_users
WHERE username = 'ART_GALLERY_OLTP';