CREATE TABLE DIM_DATE (
  DATE_KEY        NUMBER(8)      PRIMARY KEY,          
  CALENDAR_DATE   DATE           NOT NULL,
  CALENDAR_YEAR   NUMBER(4)      NOT NULL,
  CALENDAR_MONTH  NUMBER(2)      NOT NULL,
  CALENDAR_DAY    NUMBER(2)      NOT NULL,
  MONTH_NAME      VARCHAR2(20),
  QUARTER         NUMBER(1),
  IS_WEEKEND      CHAR(1)
);--


CREATE TABLE DIM_ARTIST (
  ARTIST_KEY      NUMBER          PRIMARY KEY,
  ARTIST_ID_OLTP  NUMBER,
  NAME            VARCHAR2(128)   NOT NULL,
  NATIONALITY     VARCHAR2(64),
  BIRTH_YEAR      NUMBER(4),
  DEATH_YEAR      NUMBER(4)
);

CREATE TABLE DIM_COLLECTION (
  COLLECTION_KEY      NUMBER          PRIMARY KEY,
  COLLECTION_ID_OLTP  NUMBER,
  NAME                VARCHAR2(128)   NOT NULL,
  DESCRIPTION         VARCHAR2(512),
  CREATED_DATE_KEY    NUMBER(8)      
);--no

CREATE TABLE DIM_LOCATION (
  LOCATION_KEY      NUMBER          PRIMARY KEY,
  LOCATION_ID_OLTP  NUMBER,
  NAME              VARCHAR2(128)   NOT NULL,
  GALLERY_ROOM      VARCHAR2(32),
  TYPE              VARCHAR2(32),
  CAPACITY          NUMBER
);--

CREATE TABLE DIM_EXHIBITOR (
  EXHIBITOR_KEY      NUMBER          PRIMARY KEY,
  EXHIBITOR_ID_OLTP  NUMBER,
  NAME               VARCHAR2(128)   NOT NULL,
  ADDRESS            VARCHAR2(256),
  CITY               VARCHAR2(64),
  CONTACT_INFO       VARCHAR2(256)
);--no

CREATE TABLE DIM_EXHIBITION (
  EXHIBITION_KEY      NUMBER          PRIMARY KEY,
  EXHIBITION_ID_OLTP  NUMBER,
  TITLE               VARCHAR2(128)   NOT NULL,
  START_DATE_KEY      NUMBER(8),
  END_DATE_KEY        NUMBER(8),
  EXHIBITOR_KEY       NUMBER,
  DESCRIPTION         VARCHAR2(512)
);--
--exhibition.description nu e in analiza

CREATE TABLE DIM_ARTWORK (
  ARTWORK_KEY       NUMBER          PRIMARY KEY,
  ARTWORK_ID_OLTP   NUMBER,
  TITLE             VARCHAR2(128)   NOT NULL,
  ARTIST_KEY        NUMBER          NOT NULL,
  YEAR_CREATED      NUMBER(4),
  MEDIUM            VARCHAR2(64),
  COLLECTION_KEY    NUMBER,
  LOCATION_KEY      NUMBER,
  ESTIMATED_VALUE   NUMBER(12,2)
);--

CREATE TABLE DIM_POLICY (
  POLICY_KEY          NUMBER          PRIMARY KEY,
  POLICY_ID_OLTP      NUMBER,
  PROVIDER            VARCHAR2(128)   NOT NULL,
  START_DATE_KEY      NUMBER(8),
  END_DATE_KEY        NUMBER(8),
  TOTAL_COVERAGE_AMT  NUMBER(14,2)
);--no

CREATE TABLE FACT_EXHIBITION_ACTIVITY (
  FACT_KEY               NUMBER        PRIMARY KEY,
  DATE_KEY               NUMBER(8)     NOT NULL,  
  EXHIBITION_KEY         NUMBER        NOT NULL,
  EXHIBITOR_KEY          NUMBER        NOT NULL,
  ARTWORK_KEY            NUMBER        NOT NULL,
  ARTIST_KEY             NUMBER        NOT NULL,
  COLLECTION_KEY         NUMBER,
  LOCATION_KEY           NUMBER,
  POLICY_KEY             NUMBER,

  ESTIMATED_VALUE        NUMBER(12,2),
  INSURED_AMOUNT         NUMBER(14,2),
  LOAN_FLAG              NUMBER(1),      
  RESTORATION_COUNT      NUMBER(10),     
  REVIEW_COUNT           NUMBER(10),
  AVG_RATING             NUMBER(5,2)
);
