/*
================================================================================
  ART GALLERY DW/BI - MIGRATION SCRIPT
  
  PURPOSE: 
  Migrate existing DW data to use the new ETL system with proper surrogate keys.
  
  This script should be run ONCE after deploying 5_etl_procedures.sql to:
  1. Initialize sequences to avoid conflicts with existing data
  2. Create OLTP ID indexes on dimension tables
  3. Backfill any missing dimension records
  
  Author: Oracle PL/SQL ETL Specialist
  Version: 1.0.0 - Production Grade for Master's Thesis
================================================================================
*/

SET SERVEROUTPUT ON SIZE UNLIMITED;

DECLARE
    v_max_key NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== Initializing Sequences from Existing Data ===');
    
    -- DIM_ARTIST
    SELECT NVL(MAX(ARTIST_KEY), 0) + 1 INTO v_max_key FROM DIM_ARTIST;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_DIM_ARTIST RESTART START WITH ' || v_max_key;
    DBMS_OUTPUT.PUT_LINE('SEQ_DIM_ARTIST starting from: ' || v_max_key);
    
    -- DIM_COLLECTION
    SELECT NVL(MAX(COLLECTION_KEY), 0) + 1 INTO v_max_key FROM DIM_COLLECTION;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_DIM_COLLECTION RESTART START WITH ' || v_max_key;
    DBMS_OUTPUT.PUT_LINE('SEQ_DIM_COLLECTION starting from: ' || v_max_key);
    
    -- DIM_LOCATION
    SELECT NVL(MAX(LOCATION_KEY), 0) + 1 INTO v_max_key FROM DIM_LOCATION;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_DIM_LOCATION RESTART START WITH ' || v_max_key;
    DBMS_OUTPUT.PUT_LINE('SEQ_DIM_LOCATION starting from: ' || v_max_key);
    
    -- DIM_EXHIBITOR
    SELECT NVL(MAX(EXHIBITOR_KEY), 0) + 1 INTO v_max_key FROM DIM_EXHIBITOR;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_DIM_EXHIBITOR RESTART START WITH ' || v_max_key;
    DBMS_OUTPUT.PUT_LINE('SEQ_DIM_EXHIBITOR starting from: ' || v_max_key);
    
    -- DIM_EXHIBITION
    SELECT NVL(MAX(EXHIBITION_KEY), 0) + 1 INTO v_max_key FROM DIM_EXHIBITION;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_DIM_EXHIBITION RESTART START WITH ' || v_max_key;
    DBMS_OUTPUT.PUT_LINE('SEQ_DIM_EXHIBITION starting from: ' || v_max_key);
    
    -- DIM_ARTWORK
    SELECT NVL(MAX(ARTWORK_KEY), 0) + 1 INTO v_max_key FROM DIM_ARTWORK;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_DIM_ARTWORK RESTART START WITH ' || v_max_key;
    DBMS_OUTPUT.PUT_LINE('SEQ_DIM_ARTWORK starting from: ' || v_max_key);
    
    -- DIM_POLICY
    SELECT NVL(MAX(POLICY_KEY), 0) + 1 INTO v_max_key FROM DIM_POLICY;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_DIM_POLICY RESTART START WITH ' || v_max_key;
    DBMS_OUTPUT.PUT_LINE('SEQ_DIM_POLICY starting from: ' || v_max_key);
    
    -- FACT_EXHIBITION_ACTIVITY
    SELECT NVL(MAX(FACT_KEY), 0) + 1 INTO v_max_key FROM FACT_EXHIBITION_ACTIVITY;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_FACT_EXHIBITION RESTART START WITH ' || v_max_key;
    DBMS_OUTPUT.PUT_LINE('SEQ_FACT_EXHIBITION starting from: ' || v_max_key);
    
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('=== Sequence Initialization Complete ===');
END;
/

-- Create indexes if they don't exist (safe re-run)
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_DIM_ARTIST_OLTP ON DIM_ARTIST(ARTIST_ID_OLTP)';
    DBMS_OUTPUT.PUT_LINE('Created IDX_DIM_ARTIST_OLTP');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN 
        DBMS_OUTPUT.PUT_LINE('IDX_DIM_ARTIST_OLTP already exists');
    ELSE RAISE; 
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_DIM_COLLECTION_OLTP ON DIM_COLLECTION(COLLECTION_ID_OLTP)';
    DBMS_OUTPUT.PUT_LINE('Created IDX_DIM_COLLECTION_OLTP');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN 
        DBMS_OUTPUT.PUT_LINE('IDX_DIM_COLLECTION_OLTP already exists');
    ELSE RAISE; 
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_DIM_LOCATION_OLTP ON DIM_LOCATION(LOCATION_ID_OLTP)';
    DBMS_OUTPUT.PUT_LINE('Created IDX_DIM_LOCATION_OLTP');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN 
        DBMS_OUTPUT.PUT_LINE('IDX_DIM_LOCATION_OLTP already exists');
    ELSE RAISE; 
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_DIM_EXHIBITOR_OLTP ON DIM_EXHIBITOR(EXHIBITOR_ID_OLTP)';
    DBMS_OUTPUT.PUT_LINE('Created IDX_DIM_EXHIBITOR_OLTP');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN 
        DBMS_OUTPUT.PUT_LINE('IDX_DIM_EXHIBITOR_OLTP already exists');
    ELSE RAISE; 
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_DIM_EXHIBITION_OLTP ON DIM_EXHIBITION(EXHIBITION_ID_OLTP)';
    DBMS_OUTPUT.PUT_LINE('Created IDX_DIM_EXHIBITION_OLTP');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN 
        DBMS_OUTPUT.PUT_LINE('IDX_DIM_EXHIBITION_OLTP already exists');
    ELSE RAISE; 
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_DIM_ARTWORK_OLTP ON DIM_ARTWORK(ARTWORK_ID_OLTP)';
    DBMS_OUTPUT.PUT_LINE('Created IDX_DIM_ARTWORK_OLTP');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN 
        DBMS_OUTPUT.PUT_LINE('IDX_DIM_ARTWORK_OLTP already exists');
    ELSE RAISE; 
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_DIM_POLICY_OLTP ON DIM_POLICY(POLICY_ID_OLTP)';
    DBMS_OUTPUT.PUT_LINE('Created IDX_DIM_POLICY_OLTP');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN 
        DBMS_OUTPUT.PUT_LINE('IDX_DIM_POLICY_OLTP already exists');
    ELSE RAISE; 
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IDX_FACT_BUSINESS_KEY ON FACT_EXHIBITION_ACTIVITY(ARTWORK_KEY, EXHIBITION_KEY)';
    DBMS_OUTPUT.PUT_LINE('Created IDX_FACT_BUSINESS_KEY');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN 
        DBMS_OUTPUT.PUT_LINE('IDX_FACT_BUSINESS_KEY already exists');
    ELSE RAISE; 
    END IF;
END;
/

COMMIT;

DBMS_OUTPUT.PUT_LINE('');
DBMS_OUTPUT.PUT_LINE('=== Migration Complete - Ready for ETL_SYNC_ALL ===');
/
